In [1]:
import os
os.getcwd()

'/home/pkongsomjit/Projects/softprompt_experiments/src/softprompt_experiments'

In [2]:
import pandas as pd

df = pd.read_json("/home/pkongsomjit/Projects/softprompt_experiments/master_verbalizations_w_new_soft.json")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   task_name                     96 non-null     object
 1   hard_prompt                   96 non-null     object
 2   instances                     96 non-null     object
 3   mapper_verbalization          96 non-null     object
 4   inspect_verbalization         96 non-null     object
 5   mapper_task_rougeL            96 non-null     float64
 6   soft_task_rougeL              96 non-null     float64
 7   control_task_rougeL           96 non-null     float64
 8   inspect_task_rougeL           96 non-null     float64
 9   fs_task_rougeL                96 non-null     float64
 10  mapper_verbalization_rougeL   96 non-null     float64
 11  inspect_verbalization_rougeL  96 non-null     float64
 12  soft2_task_rougeL             96 non-null     float64
dtypes: float64(8), object(5)
memory usage: 9.9+ KB

In [4]:
df.sort_values(by='soft2_task_rougeL', ascending=False)[['soft2_task_rougeL', 'task_name', 'hard_prompt','instances']].head()

,soft2_task_rougeL,task_name,hard_prompt,instances
7,1.0,task1153_bard_analogical_reasoning_affordance,Two analogies that signify affordances are giv...,"[{'input': 'ride : horse. drink : ?', 'output'..."
9,1.0,task1155_bard_analogical_reasoning_trash_or_tr...,Two analogies that relate items to whether the...,"[{'input': 'crumbs : trash. remote : ?', 'outp..."
14,1.0,task1195_disflqa_disfluent_to_fluent_conversion,"Given a disfluent sentence, modify the sentenc...",[{'input': 'What do lobates run or uh feed on?...
30,1.0,task1516_imppres_naturallanguageinference,"In this task, you are given a premise and hypo...",[{'input': 'Premise : 'All eight projectors th...
88,1.0,task828_copa_commonsense_cause_effect,In this task your given two statements. You mu...,[{'input': 'The child woke up screaming. He ha...

In [5]:
df['soft2_task_rougeL'].mean()

np.float64(0.6157087790010417)

In [6]:
tasks_translator_beat_soft = df[df['mapper_task_rougeL'] > df['soft2_task_rougeL']][['task_name', 'mapper_task_rougeL', 'soft2_task_rougeL']]

In [12]:
tasks_translator_beat_soft['winning_margin'] = df['mapper_task_rougeL'] - df['soft2_task_rougeL']

In [14]:
sorted_tasks_translator_beat_soft = tasks_translator_beat_soft.sort_values(by='winning_margin', ascending=False)

In [15]:
sorted_tasks_translator_beat_soft

,task_name,mapper_task_rougeL,soft2_task_rougeL,winning_margin
64,task349_squad2.0_answerable_unanswerable_quest...,0.900000,0.200000,7.000000e-01
48,task199_mnli_classification,0.700000,0.300000,4.000000e-01
67,task392_inverse_causal_relationship,0.866667,0.533333,3.333333e-01
42,task1624_disfl_qa_question_yesno_classification,1.000000,0.700000,3.000000e-01
24,task1390_wscfixed_coreference,0.600000,0.300000,3.000000e-01
5,task050_multirc_answerability,0.800000,0.600000,2.000000e-01
29,task1442_doqa_movies_isanswerable,0.800000,0.700000,1.000000e-01
84,task677_ollie_sentence_answer_generation,0.386262,0.305128,8.113317e-02
52,task219_rocstories_title_answer_generation,0.092710,0.040000,5.271008e-02
26,task1407_dart_question_generation,0.476581,0.441058,3.552242e-02
77,task613_politifact_text_generation,0.032749,0.000000,3.274854e-02
66,task391_causal_relationship,0.866667,0.866667,5.170000e-08

In [26]:
sorted_tasks_translator_beat_soft['task_name'].iloc[0]

'task349_squad2.0_answerable_unanswerable_question_classification'

In [27]:
df['soft2_task_rougeL'].mean()

np.float64(0.6157087790010417)

In [28]:
df['fs_task_rougeL'].mean()

np.float64(0.6702665861604168)